name: Main flow  
on: [push]

jobs: 
  test:
    name: Run tests
    strategy: 
      matrix:
        dc: [dmd-latest]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: install make etc
        run:
          sudo apt-get install build-essential

      - name: run the tests
        run:
          make NNG_WITH_MBEDTLS=OFF